heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running Gitlab

parameters:

  server_hostname:
    label: Server Name
    description: Hostname to use for setting the server name.
    type: string
    default: gitlab
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Server Image
    description: Operating system to use for the Gitlab Server
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 14.04 LTS (Trusty Tahr)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Cloud Server flavor
    description: Flavor of Cloud server to use
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  ssh_keypair_name:
    label: SSH Keypair Name
    description: New nova keypair name for ssh access to the server
    type: string
    default: gitlab-key
    constraints:
    - allowed_pattern: "^(.){1,64}$"
      description: "Must be shorter than 64 characters or fewer."

  kitchen:
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/gitlab.git

  chef_version:
    description: Version of chef client to use
    type: string
    default: 11.12.2

  gitlab_admin_user:
    description: User name for gitlab admin user
    type: string
    default: root

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  gitlab_admin_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  gitlab_db_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  mysql_debian_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  mysql_repl_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  mysql_root_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  gitlab_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }

  gitlab_presetup:
    type: "OS::Heat::ChefSolo"
    depends_on: gitlab_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [gitlab_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        run_list:
          - recipe[apt]
          - recipe[build-essential]

  gitlab_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: gitlab_presetup
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [gitlab_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        gitlab:
          admin_password: { get_attr: [gitlab_admin_password, value] }
          admin_user: { get_param: gitlab_admin_user }
          database:
            password: { get_attr: [gitlab_db_password, value] }
          generate_self_signed_cert: true
          https: true
          self_signed_cert: true
        mysql:
          server_debian_password: { get_attr: [mysql_debian_password, value] }
          server_repl_password: { get_attr: [mysql_repl_password, value] }
          server_root_password: { get_attr: [mysql_root_password, value] }
        redisio:
          servers:
            - address: 127.0.0.1
              port: 6379
        run_list:
          - recipe[mysql::server]
          - recipe[dotmy-cnf]
          - recipe[postfix::server]
          - recipe[rax-gitlab::default]
          - recipe[rax-gitlab::firewall]
          - recipe[gitlab-http-redirect]


outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    value: { get_attr: [gitlab_server, accessIPv4] }

  gitlab_admin_user:
    value: { get_param: gitlab_admin_user }

  gitlab_admin_password:
    value: { get_attr: [gitlab_admin_password, value] }
